# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='location',
            new_name='location_and_category',
        ),
    ]
