# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180103_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='location_and_category',
            new_name='location_and_Category',
        ),
    ]
