# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180103_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
