# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180103_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='claimer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
