# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20180107_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
