# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
