# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20180108_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
